title: Hello, world! I'm Tadele Belay TULI
description: > # this means to ignore newlines until "baseurl:"
  I am a researcher in the fields of humans and robots interaction in smart and virtual environment. I am interested in solving real-time problems and challenges. 
  Specifically, related to human motion modelling, humans and robots collaboration and interaction and object detection for industrial applications. I have project experience in Python, Matlab, and C#. I used OpenCV, Unity3D, ROS and Process simulate applications during my projects.
  Academically, I have successfully completed B.Sc. in Mechanical Engineering, M.Sc. in Manufacturing Engineering and M.Sc. in Mechatronics Engineering from different universities in Ethiopia and Italy. Currently, I am fully engaged on doctoral research toward my Ph.D. in the University of Siegen, Germany.At the University of Siegen, I am engaged in teaching undergraduate and graduate courses such as Industrial robotics (B.Sc. Mechanical Engineering), Automation and Industrial Communication Part II (M.Sc. Mechatronics Engineering), and Automation and Production Process (B.Sc. Mechanical), and various thesis projects.In the future, not limited to but I am interested more to focus on the development of human motion behaviour for machines and robots collaboration using artificial intelligence techniques, as well as in virtual reality environments.

permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tadeletuli.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: TadeleTuli #if your site has a twitter account, enter it here

# Author Settings
author: Tadele Belay TULI # add your name
author-img: Tuli.jpg # add your photo
about-author: I am an engineer, researcher and lecturer in Automation, Robotics and Human motion field.  # add description
social-twitter: tadeleTuli # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: TadeleTuli # add your Github handle
social-linkedin: tadele-belay-tuli-76322258 # add your Linkedin handle
academic-orcid: #0000-0002-6769-0646 # add your ORCID ID
academic-scholar: citations?user=1E7yz60AAAAJ&hl=en # add your google scholar ID
academic-publons: researcher/3205235/tadele-belay-tuli # add your Publon ID
academic-researchgate: #profile/Tadele-Tuli-2 #Add your researchgate ID
# Disqus
#discus-identifier: mr-tuli # add your discus identifier

# Tracker
analytics: 3I5qQvWaUBirDQViCSycRs91-x1Yr1YRI-oSewLLuX8 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll/scholar

require: 'jekyll/scholar'

future: true

scholar:
  style: 
  locale: en

  sort_by: none
  order: descending
  type_order: [misc, patent, techreport, thesis, book, inbook, inproceedings, article]

  source: _bibliography
  bibliography: MyPublications.bib

  details_dir: bibliography
  bibliography_template: bibliography
 
 

  query: "@*"  


paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]